creation_rules:
  - path_regex: .*secrets?.yaml
    encrypted_regex: ^(data|stringData)$
    azure_keyvault: https://k8s-training.vault.azure.net/keys/Dev-Sops/3806b6b5836f46dc96a57523c1a583e0
    age: age135nv5rzfew2wu5htvrmuf8j66yhpatnz4uatwrk8clwyjrmeq9pq6z72tp
  - path_regex: .*secretvalue.yaml
    azure_keyvault: https://k8s-training.vault.azure.net/keys/Dev-Sops/3806b6b5836f46dc96a57523c1a583e0
    age: age135nv5rzfew2wu5htvrmuf8j66yhpatnz4uatwrk8clwyjrmeq9pq6z72tp
  - path_regex: .*.env
    azure_keyvault: https://k8s-training.vault.azure.net/keys/Dev-Sops/3806b6b5836f46dc96a57523c1a583e0
    age: age135nv5rzfew2wu5htvrmuf8j66yhpatnz4uatwrk8clwyjrmeq9pq6z72tp
